config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'calendars#index'
  resources :users,          only: [:new, :create]
  resources :tasks,          only: [:new, :create, :show, :destroy, :edit, :update]
  resources :activities,     only: [:new, :create, :show, :destroy, :edit, :update]
  resources :events,          only: [:new, :create, :show, :destroy, :edit, :update]
  get   '/profile',  to: 'users#index'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/controllers/calendar_controller.rb
class CalendarsController < ApplicationController
  def show
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  def index
  end
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/views/calendars/_events.html.erb
<div class='col m12 l4'>
  <div class='card'>
    <div class='card-content'>
      <div class="row">
        <div class="col l12">
          <ul class="tabs">
            <li class="tab col s6"><a href="#tasks-tab" class='active'>Tasks</a></li>
            <li class="tab col s6"><a href="#activities-tab">Activities</a></li>
          </ul>
        </div>
        <div id="tasks-tab" class="col l12">
          <table class='highlight'>
            <thead>
              <tr>
                <th>
                  Task
                </th>
                <th>Due</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% if current_user.tasks.empty? %>
                <tr>
                  <td>No tasks!</td>
                  <td></td>
                  <td></td>
                </tr>
              <% else %>
                <% current_user.tasks.order(due_at: :asc).each do |task| %>
                  <tr>
                    <td><%= task.title %></td>
                    <% if task.due_at < Time.now %>
                      <td><%= time_ago_in_words task.due_at %> ago</td>
                    <% else %>
                      <td>in <%= distance_of_time_in_words(Time.now, task.due_at) %></td>
                    <% end %>
                    <td>
                      <%= link_to task_path(task), method: :delete do %>
                        <i class="material-icons">cancel</i>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
          <br />
          <%= link_to '+ Task', new_task_path, class:'btn' %>
        </div>
        <div id="activities-tab" class="col l12">
          <table class='highlight'>
            <thead>
              <tr>
                <th>Task</th>
                <th>Due</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Exam</td>
                <td>in 2 days</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/calendars/_list.html.erb
<div class='col m12 l4'>
  <div class='card'>
    <div class='card-content'>
      <div class="row">
        <div class="col l12">
          <ul class="tabs">
            <li class="tab col s6"><a href="#tasks-tab" class='active'>Tasks</a></li>
            <li class="tab col s6"><a href="#activities-tab">Activities</a></li>
          </ul>
        </div>
        <div id="tasks-tab" class="col l12">
          <table class='highlight'>
            <thead>
              <tr>
                <th>
                  Task
                </th>
                <th>Due</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% if current_user.tasks.empty? %>
                <tr>
                  <td>No tasks!</td>
                  <td></td>
                  <td></td>
                </tr>
              <% else %>
                <% current_user.tasks.order(due_at: :asc).each do |task| %>
                  <tr>
                    <td><%= link_to task.title, task_path(task) %></td>
                    <% if task.due_at.to_date < Time.now.in_time_zone("UTC").to_date %>
                      <td><%= time_ago_in_words task.due_at.to_date %> ago</td>
                    <% elsif task.due_at.to_date == Time.now.in_time_zone("UTC").to_date %>
                      <td>today</td>
                    <% else %>
                      <td>in <%= distance_of_time_in_words(Time.now.in_time_zone("UTC").to_date, task.due_at.to_date) %></td>
                    <% end %>
                    <td>
                      <%= link_to task_path(task), method: :delete do %>
                        <i class="material-icons">cancel</i>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
          <br />
          <div class='center-align'>
            <%= link_to '+ Task', new_task_path, class:'btn' %>
          </div>
        </div>
        <div id="activities-tab" class="col l12">
          <table class='highlight'>
            <thead>
              <tr>
                <th>Activity</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% if current_user.activities.empty? %>
                <tr>
                  <td>No activities!</td>
                  <td></td>
                </tr>
              <% else %>
                <% current_user.activities.order(title: :asc).each do |activity| %>
                  <tr>
                    <td><%= link_to activity.title, activity_path(activity) %></td>
                    <td>
                      <%= link_to activity_path(activity), method: :delete do %>
                        <i class="material-icons">cancel</i>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
          <br />
          <div class='center-align'>
            <%= link_to '+ Activity', new_activity_path, class:'btn' %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/calendars/index.html.erb
<div class='row' style='margin-top:2rem'>
  <div class='col m12 l8'>
    <div class='card'>
      <div class='card-content'>
        <div class='card-title center-align'>
          Hi <%= current_user.name %>! Have a good week
          <i class="material-icons" style='position: relative; top: 3px;'>sentiment_very_satisfied</i>
        </div>
        <table>
          <thead>
            <tr>
              <th>Monday</th>
              <th>Tuesday</th>
              <th>Wednesday</th>
              <th>Thursday</th>
              <th>Friday</th>
              <th>Saturday</th>
              <th>Sunday</th>
            </tr>
          </thead>
          <tbody>
            <% number_of_rows.times.each do |n| %>
              <tr>
                <% monday = monday_events[n] %>
                <td class=<%= event_class(monday) %> >
                  <% if monday %>
                    <p><%= link_to monday&.title, event_path(monday) %></p>
                    <p>
                      <%= monday&.starts_at&.strftime('%H:%M') %> - <%= monday&.ends_at&.strftime('%H:%M') %>
                      <%= link_to event_path(monday), method: :delete, class: 'right' do %>
                        <i class="material-icons">cancel</i>
                      <% end %>
                    </p>
                  <% end %>
                </td>
                <% tuesday = tuesday_events[n] %>
                <td class=<%= event_class(tuesday) %> >
                  <% if tuesday %>
                    <p><%= link_to tuesday&.title, event_path(tuesday) %></p>
                    <p>
                      <%= tuesday&.starts_at&.strftime('%H:%M') %> - <%= tuesday&.ends_at&.strftime('%H:%M') %>
                      <%= link_to event_path(tuesday), method: :delete, class: 'right' do %>
                        <i class="material-icons">cancel</i>
                      <% end %>
                    </p>
                  <% end %>
                </td>
                <% wednesday = wednesday_events[n] %>
                <td class=<%= event_class(wednesday) %> >
                  <% if wednesday %>
                    <p><%= link_to wednesday&.title, event_path(wednesday) %></p>
                    <p>
                      <%= wednesday&.starts_at&.strftime('%H:%M') %> - <%= wednesday&.ends_at&.strftime('%H:%M') %>
                      <%= link_to event_path(wednesday), method: :delete, class: 'right' do %>
                        <i class="material-icons">cancel</i>
                      <% end %>
                    </p>
                  <% end %>
                </td>
                <% thursday = thursday_events[n] %>
                <td class=<%= event_class(thursday) %> >
                  <% if thursday %>
                    <p><%= link_to thursday&.title, event_path(thursday) %></p>
                    <p>
                      <%= thursday&.starts_at&.strftime('%H:%M') %> - <%= thursday&.ends_at&.strftime('%H:%M') %>
                      <%= link_to event_path(thursday), method: :delete, class: 'right' do %>
                        <i class="material-icons">cancel</i>
                      <% end %>
                    </p>
                  <% end %>
                </td>
                <% friday = friday_events[n] %>
                <td class=<%= event_class(friday) %> >
                  <% if friday %>
                    <p><%= link_to friday&.title, event_path(friday) %></p>
                    <p>
                      <%= friday&.starts_at&.strftime('%H:%M') %> - <%= friday&.ends_at&.strftime('%H:%M') %>
                      <%= link_to event_path(friday), method: :delete, class: 'right' do %>
                        <i class="material-icons">cancel</i>
                      <% end %>
                    </p>
                  <% end %>
                </td>
                <% saturday = saturday_events[n] %>
                <td class=<%= event_class(saturday) %> >
                  <% if saturday %>
                    <p><%= link_to saturday&.title, event_path(saturday) %></p>
                    <p>
                      <%= saturday&.starts_at&.strftime('%H:%M') %> - <%= saturday&.ends_at&.strftime('%H:%M') %>
                      <%= link_to event_path(saturday), method: :delete, class: 'right' do %>
                        <i class="material-icons">cancel</i>
                      <% end %>
                    </p>
                  <% end %>
                </td>
                <% sunday = sunday_events[n] %>
                <td class=<%= event_class(sunday) %> >
                  <% if sunday %>
                    <p><%= link_to sunday&.title, event_path(sunday) %></p>
                    <p>
                      <%= sunday&.starts_at&.strftime('%H:%M') %> - <%= sunday&.ends_at&.strftime('%H:%M') %>
                      <%= link_to event_path(sunday), method: :delete, class: 'right' do %>
                        <i class="material-icons">cancel</i>
                      <% end %>
                    </p>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <br />
        <div class='center-align'>
          <%= link_to '+ Event', new_event_path, class:'btn' %>
        </div>
      </div>
    </div>
  </div>
  <%= render "list" %>
</div>