config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'calendars#index'
  resources :users,          only: [:new, :create]
  resources :tasks,          only: [:new, :create, :show, :destroy, :edit, :update]
  resources :activities,     only: [:new, :create, :show, :destroy, :edit, :update]
  resources :events,          only: [:new, :create, :show, :destroy, :edit, :update]
  get   '/profile',  to: 'users#index'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  validates :title,       presence: true, length: { maximum: 20 }
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(activity_params)
    @activity.user_id = session[:user_id]
    if @activity.save
      redirect_to root_path, flash: {notice: 'Successfully added activity!'}
    else
      render 'new'
    end
  end

  def edit
    @activity = @current_user.activities.find(params[:id])
  end

  def update
    @activity = @current_user.activities.find(params[:activity][:id])
    if @activity.update_attributes(activity_params)
      redirect_to activity_path(@activity), flash: {notice: 'Successfully edited activity!'}
    else
      render 'edit'
    end
  end

  def show
    @activity = @current_user.activities.find(params[:id])
  end

  def destroy
    @activity = @current_user.activities.find(params[:id])
    if @activity.destroy
      flash[:notice] = 'Successfully deleted activity!'
    else
      flash[:alert] = "Unable to delete activity: #{@activity.errors.full_messages.join(', ')}"
    end
    redirect_to root_path
  end

private

  def activity_params
    params.require(:activity).permit(:title, :description)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class='col s12 m8 l6 offset-m2 offset-l3'>
      <div class='card' style='margin-top: 2rem'>
        <div class='card-content'>
          <div class='card-title center-align'>Edit Activity</div>
          <%= form_for(@activity) do |f| %>
            <%= render 'shared/error_messages' %>
            <div class='input-field'>
              <%= f.label :title %>
              <%= f.text_field :title, class: 'form-control' %>
            </div>
            <div class='input-field'>
              <%= f.label :description %>
              <%= f.text_field :description, class: 'form-control' %>
            </div>
            <%= f.hidden_field :id, :value => @activity.id %>
            <div class='center-align'>
              <%= f.submit "Update activity", class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/activities/new.html.erb
<div class='container'>
  <div class='row'>
    <div class='col s12 m8 l6 offset-m2 offset-l3'>
      <div class='card' style='margin-top: 2rem'>
        <div class='card-content'>
          <div class='card-title center-align'>New Activity</div>
          <%= form_for(@activity) do |f| %>
            <%= render 'shared/error_messages' %>
            <div class='input-field'>
              <%= f.label :title %>
              <%= f.text_field :title, class: 'form-control' %>
            </div>
            <div class='input-field'>
              <%= f.label :description %>
              <%= f.text_field :description, class: 'form-control' %>
            </div>
            <div class='center-align'>
              <%= f.submit "Create activity", class: "btn btn-primary" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/activities/show.html.erb
<div class='row'>
  <div class='col l4 offset-l4 m8 offset-m2 s12'>
    <div class='card'>
      <div class='card-content'>
        <div class='center-align card-title'><%= @activity.title %></div>
        <p>description:</p>
        <p><%= @activity.description %></p>
      </div>
      <div class='card-action right-align'>
        <%= link_to "back", root_path, class:'btn-flat' %>
        <%= link_to "edit", edit_activity_path(@activity), class:'btn' %>
      </div>
    </div>
  </div>
</div>