config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'calendars#index'
  resources :users,          only: [:new, :create]
  resources :tasks,          only: [:new, :create, :show, :destroy, :edit, :update]
  resources :activities,     only: [:new, :create, :show, :destroy, :edit, :update]
  resources :events,          only: [:new, :create, :show, :destroy, :edit, :update]
  get   '/profile',  to: 'users#index'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scheduler</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
  </head>

  <body>
    <nav>
      <div class="nav-wrapper container">
        <%= link_to "My Week", root_path, class:"brand-logo" %>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <% if logged_in?%>
            <li><%= link_to "Calendar", root_path %></li>
            <li><a class='dropdown-trigger' href='#' data-target='dropdown1'><%= current_user.name %></a></li>
            <ul id='dropdown1' class='dropdown-content'>
              <li><%= link_to "Profile", profile_path %></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          <% else %>
            <li><%= link_to "Log in", login_path %></li>
            <li><%= link_to "Sign up", signup_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <% if flash.present? %>
      <div class='container'>
        <% flash.each do |key, msg| %>
          <div class="card horizontal closeable <%= key == 'alert' ? 'red' : 'green'  %> lighten-2">
            <div class="card-image">
              <i class="material-icons medium"><%= key == 'alert' ? 'error' : 'check' %></i>
            </div>
            <div class="card-content" style='width: 100%'>
              <div class="right">
                <a href="javascript:void(0)" data-close>
                  <span class="badge">x</span>
                </a>
              </div>
              <p><%= msg %></p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>